# Generated by Django 5.1.6 on 2025-02-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Wardrobe',
        ),
    ]
